homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

project_add:
    path: /add
    defaults: {_controller: AppBundle:ManageProjects:addProject }

project_remove:
    path: /add/remove/{idProject}
    defaults: {_controller: AppBundle:ManageProjects:removeProject }
