# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
            our_db_provider:
                entity:
                    class: AppBundle:User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            provider: our_db_provider
            logout:
                 path: app_logout